
=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

puts "\nThis program will calculate the Fibonacci sequence up to a given limit."
puts "It will then use this sequence to calculate some interesting values.\n"
print "\nPlease enter a whole number limit: "
limit = gets.chomp.to_i

fib_array = []
a, b = 0, 1
while b < limit
  fib_array.push(a)
  a, b = b, a + b
end
puts fib_array.inspect

even_sum = 0
odd_sum = 0
fib_array.each do |i|
  if i % 2 == 0
    even_sum += i
  else
    odd_sum += i
  end
end
puts "\nSum of even numbers: #{even_sum}"
puts "Sum of odd numbers: #{odd_sum}"